SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$(cd "$( dirname "${SOURCE}" )" >/dev/null && pwd)"
 
source "$DIR/bash/settings.sh"
source "$DIR/bash/funcs.sh"
source "$DIR/bash/aliases.sh"
source "$DIR/bash/prompt.sh"

bind -f "$DIR/inputrc"

# BCPC VM configuration
export no_proxy=$no_proxy,blp-dpkg.dev.bloomberg.com
export TMPDIR=/tmp

source /opt/rh/devtoolset-7/enable
