" GVim Settings
if has("gui_running")
    set guifont=Fira\ Code\ Retina\ 10
endif

" Load functions
source ~/.vim/startup/functions/vimscript-helpers.vim
source ~/.vim/startup/functions/environment.vim
source ~/.vim/startup/functions/directories.vim
source ~/.vim/startup/functions/formatting.vim

" Load each specialized settings file
source ~/.vim/startup/plugins.vim
source ~/.vim/startup/settings.vim
source ~/.vim/startup/mappings.vim

set background=dark
colorscheme one
